stages:
  data_load:
    cmd: python src/stages/data_load.py --config=params.yaml
    deps:
    - src/stages/data_load.py
    params:
    - base
    - data_load
    outs:
    - data/raw/raw_diabetes.csv

  features_load:
    cmd: python src/stages/features_load.py --config=params.yaml
    deps:
    - data/raw/raw_diabetes.csv
    - src/stages/features_load.py
    params:
    - base
    - featurize
    outs:
    - data/processed/features_diabetes.csv

  data_split:
    cmd: python src/stages/data_split.py --config=params.yaml
    deps:
    - data/processed/features_diabetes.csv
    - src/stages/data_split.py
    params:
    - base
    - data_split
    - featurize
    outs:
    - data/processed/test_diabetes.csv
    - data/processed/train_diabetes.csv

  train:
    cmd: python src/stages/train.py --config=params.yaml
    deps:
    - data/processed/train_diabetes.csv
    - src/stages/train.py
    params:
    - model
    - train
    - featurize.target_column
    - data_split.train_db
    outs:
    - models/model.joblib

  evaluate:
    cmd: python src/stages/evaluation.py --config=params.yaml
    deps:
    - data/processed/test_diabetes.csv
    - src/stages/evaluation.py
    - models/model.joblib
    params:
    - featurize.target_column
    - data_split.test_db
    - reports
    outs:
    - reports/confusion_matrix.png
    metrics:
    - reports/metrics.json:
        cache: false