base:
  random_state: 42

data_load:
  raw_db: 'data/raw/raw_diabetes.csv'

featurize:
  featurize_db: 'data/processed/features_diabetes.csv'
  target_column: target

data_split:
  test_db: 'data/processed/test_diabetes.csv'
  train_db: 'data/processed/train_diabetes.csv'
  test_size: 0.2

train:
  cv: 3
  estimators_used: xgbc
  estimators:
    xgbc:
      param_grid:
        learning_rate: [0.01, 0.001]
        max_depth: [3, 5, 8]
        n_estimators: [ 1000,1500, 2000]
    logreg:
      param_grid:
        C: [0.001, 0.01, 0.1] 
        solver: ['lbfgs']
        multi_class: ['multinomial']
        max_iter: [50, 100, 200]
    svm:
      param_grid:
        C: [0.01, 0.001]   
        kernel: ['linear', 'poly', 'rbf']
        degree: [2, 3, 4]
        gamma: ['scale']
    randomForest:
      param_grid:
        n_estimators: [200, 500, 1000]
        max_depth: [20, 30]
  

model:
  path: 'models/model.joblib'

reports:
  confusion_matrix_data: reports/confusion_matrix_data.csv
  confusion_matrix_image: 'reports/confusion_matrix.png'
  metrics_file: 'reports/metrics.json'